### ISSUE TITLE
[BUG] how do i use it?

### ISSUE THREAD

**Issue by autoteelar** [rl-os/api#110]
**Describe the bug**
idk how to download
**To Reproduce**

**Expected behavior**

**Screenshots**

**Enviroment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.03]
 - Go Version [e.g. 1.13] 
 - Python Version [e.g. 3.8]  
 - Node.JS Version [e.g. 13.1.0] 
 - Version or git commit id [e.g. 1.1.0]

**Comment by deissh** [comment]
Run `make` in bash

---

`make docker-build`
 
Or

- `make install`
- `make db-migrate`
- `make build-prod`
- `mv config.example.yaml config.yaml && vim config.yaml`
